version: '3'

services:
    db:
        container_name: database_mongo
        image: mongo

    api:
        container_name: api_main
        image: teerasej/web_api:1.1
        environment:
            - PORT=3000
            - MONGO_DB_HOST=db
            - MONGO_DB_PORT=27017
        depends_on:
            - db
        ports:
          - "3100:3000"